### ISSUE TITLE
Update to 1.2.0

### ISSUE THREAD

**Issue by BSzili** [dandar3/android-androidx-browser#1]
The latest stable version is 1.2.0 from December 18, 2019. Could you update this library?

**Comment by dandar3** [comment]
@BSzili 
Done, updated here as well as in [android-androidx-README](https://github.com/dandar3/android-androidx-README). Please let me know how it works for you.

**Comment by BSzili** [comment]
The library looks good, but I forgot that Google started using Java 8 features lately. This one uses static interface methods and invokedynamic, so I'd have to raise the min-sdk-version to 26. Anyway, the library itself is fine, I'll close the issue.
